export class Chara {
    /**
     * 
     * @param {string} id 
     * @param {string} traits 
     * @param {string} clothes 
     * @param {string} addpos 
     * @param {string} addneg 
     */
    constructor(id, traits, clothes, addpos="", addneg="") {
        this.id = id
        this.traits = traits
        this.clothes = clothes
        this.addpos = addpos
        this.addneg = addneg
    }

    /**
     * @param {number} start 
     */
    TI(start) {
        start = start > 0.99 ? 0.99 : start
        start = start < 0 ? 0 : start
        this.tis = start
        return this
    }

    id = ""
    traits = ""
    clothes = ""
    addpos = ""
    addneg = ""
    tis = 0
}

/**
 * @type {Chara[]}
 */
export let chara = [
    new Chara("nia teppelin",
        "nia teppelin, long hair, multicolored hair, symbol-shaped pupils, cross-shaped pupils, flower, hair ornament, hair flower, petite, ",
        "jewelry, pink dress, white skirt, bracelet, armlet, ",
        "<lora:nia-teppelin-ponyxl-lora-nochekaiser:1.2>, ").TI(0.99),
    new Chara("hakurei reimu", 
        "1girl, hakurei_reimu, touhou, hair_bow, red_bow, frilled_bow, frilled_hair_tubes, ", 
        "detached_sleeves, yellow_ascot, red_skirt, ribbon-trimmed_sleeves, wide_sleeves, white_sleeves, ", 
        "<lora:Touhou_pony:0.5>, "),
    new Chara("kirisame marisa", 
        "1girl, kirisame_marisa, touhou, single_braid, white_bow, hair_bow, ",
        "witch_hat, hat_bow, white_shirt, black_vest, black_hat, white_apron, black_skirt, waist_apron, puffy_short_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("rumia", 
        "1girl, rumia, touhou, hair_ribbon, red_ribbon, ",
        "long_sleeves, black_vest, white_shirt, black_skirt, red_ascot, collared_shirt",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("daiyousei", 
        "1girl, daiyousei, touhou, fairy_wings, hair_bow, yellow_bow, ", 
        "white_shirt, yellow_ascot, collared_shirt, blue_vest, blue_skirt, puffy_short_sleeves, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("cirno", 
        "1girl, cirno, touhou, blue_bow, hair_bow, ice_wings, ",
        "blue_dress, red_ribbon, puffy_short_sleeves, morning_glory, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("hong meiling", 
        "1girl, hong_meiling, touhou, twin_braids, hair_bow, black_bow, ",
        "green_hat, star_hat_ornament, white_shirt, beret, green_vest, puffy_short_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("koakuma", 
        "1girl, head_wings, koakuma, touhou, bat_wings, black_wings, ", 
        "white_shirt, red_necktie, black_vest, black_skirt, long_sleeves, collared_shirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("patchouli knowledge", 
        "1girl, patchouli_knowledge, touhou, crescent_hat_ornament, hair_bow, blue_bow, red_bow, red_ribbon, ", 
        "mob_cap, long_sleeves, vertical-striped_clothes, vertical-striped_dress, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("izayoi sakuya", 
        "1girl, izayoi_sakuya, touhou, maid_headdress, twin_braids, hair_bow, green_bow, ",
        "white_apron, waist_apron, blue_dress, puffy_short_sleeves, white_shirt, maid_apron, frilled_apron, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("remilia scarlet", 
        "1girl, remilia_scarlet, touhou, bat_wings, ", 
        "mob_cap, red_ribbon, hat_ribbon, red_ascot, puffy_short_sleeves, pink_hat, collared_shirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("flandre scarlet", 
        "1girl, flandre_scarlet, touhou, red_ribbon, crystal_wings, ", 
        "mob_cap, hat_ribbon, yellow_ascot, puffy_short_sleeves, red_skirt, white_hat, red_vest, white_shirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("letty whiterock", 
        "1girl, letty_whiterock, touhou, lapel_pin, ", 
        "white_headwear, blue_vest, white_shirt, long_sleeves, white_hat, white_apron, white_scarf, waist_apron, blue_skirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("chen", 
        "1girl, chen, touhou, two_tails, animal_ear_piercing, single_earring, nekomata, animal_ear_fluff, ",
        "mob_cap, green_hat, red_vest, red_skirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("alice margatroid", 
        "1girl, alice margatroid, touhou, red_hairband, lolita_hairband, ", 
        "bow, blue_dress, white_capelet, red_bowtie, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("lily white",
        "1girl, lily_white, touhou, fairy_wings, ", 
        "white_hat, white_dress, white_capelet, long_sleeves, wide_sleeves, red_bowtie, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("lunasa prismriver", 
        "1girl, lunasa_prismriver, touhou, ",
        "hat, long_sleeves, black_hat, black_skirt, violin, crescent, skirt_set, white_shirt, bow_(music), black_vest",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("merlin prismriver", 
        "1girl, merlin_prismriver, touhou, ",
        "hat, trumpet, long_sleeves, pink_hat, pink_skirt, pink_shirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("konpaku youmu",
        "1girl, touhou, konpaku_youmu, black_hairband, black_ribbon, hair_ribbon, ", 
        "white_shirt, green_vest, green_skirt, collared_shirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("saigyouji yuyuko",
        "1girl, saigyouji_yuyuko, touhou, ", 
        "mob_cap, triangular_headpiece, blue_hat, blue_kimono, long_sleeves, wide_sleeves, frilled_kimono, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("yakumo ran", 
        "1girl, touhou, yakumo_ran, multiple_tails, ",
        "mob_cap, white_dress, long_sleeves, white_hat, blue_tabard, wide_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("yakumo yukari", 
        "1girl, yakumo_yukari, touhou, hair_bow, red_bow, ",
        "mob_cap, hat_ribbon, red_ribbon, white_hat, purple_dress, white_gloves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("usami renko",
        "1girl, usami_renko, touhou, white_bow, hair_bow, ", 
        "hat_bow, red_necktie, white_shirt, black_hat, black_skirt, long_sleeves, fedora, collared_shirt, black_capelet ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("maribel hearn", 
        "1girl, maribel_hearn, touhou, ", 
        "mob_cap, red_ribbon, purple_dress, white_hat, long_sleeves, collared_dress, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("ibuki suika", 
        "1girl, ibuki_suika, touhou, hair_bow, red_bow, horn_ribbon, horn, ",
        "white_shirt, chain, sleeveless_shirt, purple_skirt, gourd, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("wriggle nightbug", 
        "1girl, wriggle_nightbug, touhou, antennae, ",
        "white_shirt, black_cape, collared_shirt, long_sleeves, red_cape, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("mystia lorelei", 
        "1girl, mystia_lorelei, touhou, bird_wings, white_wings, single_earring, ",
        "brown_dress, winged_hat, brown_hat, long_sleeves, white_shirt, sleeve_garter, collared_shirt, frilled_sleeves, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kamishirasawa keine", 
        "1girl, kamishirasawa_keine, touhou, horn_ribbon, horn_bow, red_bow, ", 
        "blue_dress, puffy_short_sleeves, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("inaba tewi", 
        "1girl, inaba_tewi, touhou, rabbit_girl, ", 
        "pink_dress, carrot_necklace, puffy_short_sleeves, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("reisen udongein inaba", 
        "1girl, reisen_udongein_inaba, touhou, rabbit_girl, ", 
        "red_necktie, white_shirt, collared_shirt, long_sleeves, pink_skirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("yagokoro eirin",
        "1girl, yagokoro_eirin, touhou, single_braid, large_breasts",
        "nurse_cap, blue_dress, blue_hat, red_cross, two-tone_dress, constellation_print, red_dress",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("houraisan kaguya", 
        "1girl, houraisan_kaguya, touhou, hime_cut, sidelocks, ", 
        "pink_shirt, long_sleeves, wide_sleeves, red_skirt, collared_shirt, long_skirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("fujiwara no mokou", 
        "1girl, fujiwara_no_mokou, touhou, hair_bow, white_bow, ",
        "white_shirt, red_pants, collared_shirt, suspenders, long_sleeves, ofuda_on_clothes, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("luna child", 
        "1girl, luna_child, touhou, fairy_wings, ", 
        "white_dress, white_hat, wide_sleeves, long_sleeves, hat, black_bowtie, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("star sapphire", 
        "1girl, star_sapphire, touhou, hair_bow, fairy_wings, blue_bow, sidelocks, ",
        "blue_dress, long_sleeves, wide_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("sunny milk", 
        "1girl, sunny_milk, touhou, fairy_wings, fang, two_side_up, headdress, hair_bow, ", 
        "long_sleeves, ascot, yellow_ascot, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kazami yuuka", 
        "1girl, kazami_yuuka, touhou, ",
        "white_shirt, red_vest, yellow_ascot, long_sleeves, plaid_vest, red_skirt, collared_shirt, plaid_skirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("medicine melancholy", 
        "1girl, medicine_melancholy, touhou, red_ribbon, hair_ribbon, ", 
        "red_skirt, puffy_short_sleeves, black_shirt, lily_of_the_valley, red_bowtie, frilled_shirt_collar, short_sleeves, frilled_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("onozuka komachi", 
        "1girl, onozuka_komachi, touhou, two_side_up, hair_bobbles, ", 
        "obijime, obidome, blue_dress, short_sleeves, coin_on_string, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("shameimaru aya", 
        "1girl, touhou, shameimaru_aya, ", 
        "tokin_hat, red_hat, white_shirt, pom_pom_(clothes), black_skirt, black_wings, collared_shirt, bird_wings, frilled_skirt, feathered_wings, puffy_short_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("shiki eiki", 
        "1girl, shiki_eiki, touhou, ", 
        "frilled_hat, blue_vest, rod_of_remorse, long_sleeves, black_skirt, white_shirt, epaulettes, blue_hat, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("hieda no akyuu",
        "1girl, hieda_no_akyuu, touhou, hair_flower, white_flower, ",
        "green_kimono, long_sleeves, wide_sleeves, red_skirt, yellow_kimono, floral_print, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("aki shizuha", 
        "1girl, aki_shizuha, touhou, autumn_leaves, maple_leaf, ",
        "long_sleeves, red_skirt, buttons, red_shirt, collared_shirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("aki minoriko",
        "1girl, aki_minoriko, touhou, grapes, ", 
        "mob_cap, grape_hat_ornament, fruit_hat_ornament, red_hat, red_apron, yellow_shirt, long_sleeves, black_skirt, wide_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kagiyama hina", 
        "1girl, kagiyama_hina, touhou, hair_ribbon, red_ribbon, frilled_ribbon, red_bow, hair_bow, frilled_bow, ", 
        "puffy_short_sleeves, arm_ribbon, red_dress, frilled_dress, ",
        "<lora:Touhou_pony:0.7>, "), 
    new Chara("kawashiro nitori", 
        "1girl, kawashiro_nitori, touhou, hair_bobbles, two_side_up, ", 
        "green_hat, flat_cap, key, blue_skirt, blue_shirt, backpack, long_sleeves, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("inubashiri momiji", 
        "1girl, inubashiri_momiji, touhou, wolf_girl, animal_ear_fluff, ", 
        "tokin_hat, detached_sleeves, pom_pom_(clothes), red_hat, white_shirt, black_skirt, bare_shoulders, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kochiya sanae",
        "1girl, kochiya_sanae, touhou, ", 
        "detached_sleeves, white_shirt, blue_skirt, single_hair_tube, bare_shoulders, hair_tubes, collared_shirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("yasaka kanako", 
        "1girl, yasaka_kanako, touhou, autumn_leaves, ", 
        "red_shirt, mirror, shimenawa, short_over_long_sleeves, black_skirt, shide, long_skirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("moriya suwako",
        "moriya_suwako, 1girl, touhou, ",
        "wide_sleeves, long_sleeves, purple_vest, white_shirt, brown_hat, purple_skirt, red_ribbon, white_thighhighs, frog_print, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("watatsuki no yorihime", 
        "1girl, watatsuki_no_yorihime, touhou, hair_ribbon, hair_bow, yellow_ribbon, ",
        "red_dress, belt, puffy_short_sleeves, white_shirt, bracelet, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("nagae iku", 
        "1girl, nagae_iku, touhou, red_bow, ", 
        "black_hat, hat_bow, black_skirt, long_sleeves, white_shirt, frilled_shawl, white_capelet, frilled_capelet, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("hinanawi tenshi", 
        "1girl, hinanawi_tenshi, touhou, peach, ",
        "white_shirt, black_hat, peach_hat_ornament, blue_skirt, red_bowtie, puffy_short_sleeves, collared_shirt, center_frills, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kisume", 
        "1girl, kisume, touhou, hair_bobbles, two_side_up, ",
        "in_bucket, wooden_bucket, white_kimono, long_sleeves, wide_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kurodani yamame",
        "1girl, kurodani_yamame, touhou, hair_bow, black_bow, ",
        "long_sleeves, brown_dress, black_shirt, pinafore_dress, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("mizuhashi parsee", 
        "1girl, mizuhashi_parsee, touhou, ", 
        "white_scarf, brown_shirt, short_sleeves, arm_warmers, black_shirt, black_skirt, white_sash, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("hoshiguma yuugi",
        "1girl, touhou, single_horn, hoshiguma_yuugi, star_(symbol), ",
        "sakazuki, shackles, white_shirt, chain, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("komeiji satori", 
        "1girl, komeiji_satori, touhou, third_eye, black_hairband, eyeball, ", 
        "heart_button, blue_shirt, long_sleeves, frilled_sleeves, wide_sleeves, frilled_shirt_collar, pink_skirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kaenbyou rin", 
        "1girl, kaenbyou_rin, touhou, twin_braids, cat_girl, hair_bow, two_tails, black_bow, nekomata, ",
        "green_dress, black_dress, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("reiuji utsuho",
        "1girl, reiuji_utsuho, touhou, hair_bow, green_bow, third_eye, black_wings, bird_wings, ", 
        "white_shirt, green_skirt, arm_cannon, collared_shirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("komeiji koishi", 
        "1girl, komeiji_koishi, touhou, third_eye, heart_of_string, eyeball, ", 
        "hat_bow, yellow_bow, hat_ribbon, black_hat, yellow_shirt, frilled_sleeves, frilled_shirt_collar, green_skirt, wide_sleeves, blouse, diamond_button, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("nazrin", 
        "1girl, nazrin, touhou, mouse_girl, ", 
        "long_sleeves, pendant, white_shirt, blue_capelet, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("tatara kogasa", 
        "1girl, tatara_kogasa, touhou, heterochromia, karakasa_obake, ",
        "white_shirt, blue_vest, blue_skirt, long_sleeves, juliet_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kumoi ichirin",
        "1girl, kumoi_ichirin, touhou, ",
        "hood, kesa, long_sleeves, wide_sleeves, hoop, pendant, ring, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("murasa minamitsu",
        "murasa_minamitsu, 1girl, touhou, ",
        "sailor_hat, white_shirt, red_neckerchief, white_shorts, white_hat, short_sleeves, sailor_shirt, green_sailor_collar, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("toramaru shou", 
        "1girl, toramaru_shou, touhou, ",
        "long_sleeves, tiger_print, wide_sleeves, bishamonten's_pagoda, bishamonten's_spear, red_dress, black_ribbon, hagoromo, o-ring, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("hijiri byakuren",
        "1girl, hijiri_byakuren, touhou, ",
        "white_dress, cross-laced_clothes, layered_dress, black_dress, juliet_sleeves, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("houjuu nue", 
        "1girl, houjuu_nue, touhou, asymmetrical_wings, red_wings, blue_wings, ",
        "black_dress, short_sleeves, black_thighhighs, red_bowtie, center_frills, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("himekaidou hatate", 
        "1girl, himekaidou_hatate, touhou, tokin_hat, purple_hat, ",
        "white_shirt, checkered_skirt, collared_shirt, puffy_short_sleeves, purple_skirt, black_necktie, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("ibaraki kasen",
        "1girl, ibaraki_kasen, touhou, bun_cover, bandaged_arm, ",
        "tabard, green_skirt, white_shirt, pink_rose, shackles, short_sleeves",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kasodani kyouko",
        "1girl, kasodani_kyouko, touhou", 
        "long_sleeves, pink_dress, white_socks, black_footwear, brown_dress", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("miyako yoshika", 
        "1girl, miyako_yoshika, touhou, jiangshi, star_hat_ornament, neck_ribbon, zombie_pose, black_ribbon, ", 
        "ofuda, red_shirt, cabbie_hat, short_sleeves, black_skirt, tangzhuang, purple_hat, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kaku seiga", 
        "1girl, kaku_seiga, touhou, hair_rings, hair_stick, hagoromo, ",
        "blue_dress, white_vest, puffy_short_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("soga no tojiko", 
        "1girl, soga_no_tojiko, touhou, ",
        "tate_eboshi, black_hat, green_dress, long_sleeves, ofuda_on_clothes, cross-laced_clothes, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("mononobe no futo",
        "1girl, mononobe_no_futo, touhou, ",
        "tate_eboshi, kariginu, ribbon-trimmed_sleeves, wide_sleeves, long_sleeves, pom_pom_(clothes), blue_hat, blue_skirt, black_hat, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("toyosatomimi no miko", 
        "1girl, toyosatomimi_no_miko, touhou, earmuffs, ",
        "bracelet, sleeveless_shirt, purple_skirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("futatsuiwa mamizou", 
        "1girl, touhou, futatsuiwa_mamizou, glasses, leaf_on_head, raccoon_girl, ",
        "brown_shirt, short_sleeves, brown_skirt, tokkuri, holding_smoking_pipe, kiseru, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("motoori kosuzu", 
        "1girl, motoori_kosuzu, touhou, hair_bell, two_side_up, jingle_bell, ",
        "checkered_kimono, yellow_apron, long_sleeves, wide_sleeves, green_skirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("hata no kokoro", 
        "1girl, hata_no_kokoro, touhou, mask_on_head, expressionless, ", 
        "plaid_shirt, long_sleeves, orange_skirt, bubble_skirt, collared_shirt, aqua_shirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("wakasagihime", 
        "1girl, wakasagihime, touhou, head_fins, drill_sidelocks, ", 
        "green_kimono, long_sleeves, wide_sleeves, frilled_kimono, obi, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("sekibanki",
        "1girl, touhou, sekibanki, hair_bow, blue_bow, ", 
        "long_sleeves, black_shirt, red_skirt, red_cape, cloak, rock_'n'_rock_'n'_beat, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("imaizumi kagerou", 
        "1girl, imaizumi_kagerou, touhou, wolf_girl, animal_ear_fluff, red_nails, ",
        "white_dress, long_sleeves, brooch, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("tsukumo benben", 
        "1girl, tsukumo_benben, touhou, hair_flower, white_flower, ", 
        "long_sleeves, biwa_lute, barefoot, brown_dress, chain, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kijin seija", 
        "1girl, kijin_seija, touhou, ", 
        "white_dress, short_sleeves, puffy_short_sleeves, white_shirt, bracelet", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("sukuna shinmyoumaru", 
        "1girl, sukuna_shinmyoumaru, touhou, ", 
        "bowl_hat, long_sleeves, wide_sleeves, red_kimono, obi, black_hat, barefoot, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("horikawa raiko", 
        "1girl, horikawa_raiko, touhou, ",
        "purple_necktie, white_jacket, long_sleeves, plaid_shirt, black_shirt, white_skirt, collared_shirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("usami sumireko",
        "1girl, usami_sumireko, touhou, glasses, red-framed_eyewear, under-rim_eyewear, ",
        " hat_bow, white_bow, black_hat, white_shirt, long_sleeves, plaid_vest, purple_vest, plaid_skirt, purple_skirt",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("doremy sweet", 
        "1girl, doremy_sweet, touhou, ",
        "pom_pom_(clothes), nightcap, red_hat, white_dress, black_capelet, black_dress, multicolored_dress, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kishin sagume",
        "1girl, kishin_sagume, touhou, single_wing, feathered_wings, white_wings, french_braid, angel_wings, ", 
        "purple_dress, long_sleeves, red_bowtie, open_jacket, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("clownpiece", 
        "clownpiece, 1girl, touhou, jester_cap, polka_dot_headwear, purple_hat, fairy_wings, ", 
        "star_print, striped_clothes, american_flag_dress, american_flag_legwear, striped_dress, short_sleeves, neck_ruff, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("hecatia lapislazuli",
        "1girl, hecatia_lapislazuli, touhou, earth_(ornament), moon_(ornament), underworld_(ornament), black_headwear, ", 
        "bare_shoulders, clothes_writing, black_shirt, off-shoulder_shirt, t-shirt, short_sleeves, multicolored_skirt, plaid_skirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("yorigami jo'on", 
        "1girl, yorigami_jo'on, touhou, twin_drills, eyewear_on_head, sunglasses, earrings, round_eyewear, ", 
        "white_dress, necklace, top_hat, purple_coat, black_hat, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("yorigami shion", 
        "1girl, yorigami_shion, touhou, hair_bow, blue_bow, debt", 
        "grey_hoodie, blue_skirt, short_sleeves, bangle",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("eternity larva", 
        "1girl, eternity_larva, touhou, insect_wings, butterfly_wings, antennae, leaf_on_head, fairy, ", 
        "green_dress, short_sleeves, multicolored_dress, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("komano aunn",
        "1girl, komano_aunn, touhou, single_horn, ", 
        "kariyushi_shirt, white_shorts, cloud_print, short_sleeves, collared_shirt, red_shirt, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("matara okina", 
        "1girl, matara_okina, touhou, black_hat, brown_hat, ",
        "wide_sleeves, constellation_print, green_skirt, tabard, long_sleeves, detached_sleeves, white_shirt, orange_sleeves, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("niwatari kutaka", 
        "1girl, niwatari_kutaka, touhou, bird_wings, yellow_wings, bird_on_head, chick, feathered_wings, ",
        "white_shirt, orange_dress, short_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("kicchou yachie", 
        "1girl, kicchou_yachie, touhou, turtle_shell, antlers, dragon_girl, ", 
        "collarbone, blue_shirt, short_sleeves, green_skirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("joutouguu mayumi", 
        "1girl, joutouguu_mayumi, touhou, hair_ribbon, white_ribbon, ",
        "yellow_dress, puffy_short_sleeves, armored_dress, vambraces, white_shirt, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("haniyasushin keiki", 
        "1girl, haniyasushin_keiki, touhou, green_headwear, head_scarf, ",
        "magatama_necklace, green_apron, yellow_dress, single_strap, arm_ribbon, wood_carving_tool, blue_ribbon, tools, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("toutetsu yuuma", 
        "1girl, toutetsu_yuuma, touhou, earrings, sharp_teeth, horn_ribbon, horizontal_pupils, ", 
        "bare_shoulders, blue_dress, meandros, red_sleeves, blue_ribbon, detached_sleeves, ", 
        "<lora:Touhou_pony:0.7>, "),
    new Chara("goutokuji mike", 
        "1girl, goutokuji_mike, cat_girl, touhou, jingle_bell, neck_bell, calico, ", 
        "multicolored_shirt, crop_top, maneki-neko, patchwork_clothes, ",
        "<lora:Touhou_pony:0.7>, "),
    new Chara("tenkyuu chimata",
        "1girl, tenkyuu_chimata, touhou, multicolored_hairband, ",
        "long_sleeves, multicolored_dress, rainbow_gradient, patchwork_clothes, white_cloak, sky_print, white_cape, ",
        "<lora:Touhou_pony:0.7>, ")
]